### PR TITLE
Fix transformation of non-ASCII on Windows

### LINKED ISSUE #329: style_file() unexpectedly deletes non-ASCII characters on Windows
(Sorry, this is a "manual" reprex, as it throws errors on reading/writing to the tempfile.)

```r
tmp <- tempfile(fileext = ".R")

con <- file(tmp, encoding = "UTF-8")

# "1+1" needs spaces
writeLines("# 忍者\n1+1", con)

readLines(con)
#> [1] "# 忍者" "1+1"

styler::style_file(tmp)

#> ----------------------------------------
#> Status	Count	Legend 
#> √ 	0	File unchanged.
#> i 	1	File changed.
#> x 	0	Styling threw an eror.
#> ----------------------------------------
#> Please review the changes carefully!


# the comment "# 忍者" disappeared...
readLines(con)
# [1] ""      "1 + 1"
```

I think the root cause is this line in enc package; `from = "UTF-8"` should not set here as it seems that text is encoded as the default encoding.

https://github.com/krlmlr/enc/blob/883df89f77bb5f8646b9a8fa94cc72120cdf0c81/R/io.R#L59

### PR DESCRIPTION
**Pull request by yutannihilation**
I believe this fixes https://github.com/r-lib/styler/issues/329.

As described the original issue above, in `transform_lines_enc_one()`, there is nothing to ensure `new_text` is in the UTF-8 encoding while `write_lines_enc()` requires UTF-8.

https://github.com/krlmlr/enc/blob/883df89f77bb5f8646b9a8fa94cc72120cdf0c81/R/io.R#L109-L116

I don't see any major drawbacks to change `as.character()` to `to_utf8()`, but I'm still not sure why `as.character()` was introduced here. Shouldn't it throw an error when `fun()` returns non-characters? What cases does it consider about?

### CODE REVIEW

**Comment by yutannihilation** [comment]
@krlmlr Didn't you forget to change AppVeyor's setting when renamed to enc?

**Comment by yutannihilation** [comment]
I've confirmed the test fails with the current implementation and changing `character()` to `to_utf8()` fixes the problem on the forked repo's AppVeyor:

https://github.com/yutannihilation/enc/pull/1

File: tests/testthat/test-transform-lines.R [hunk 1]
```diff
@@ -88,6 +90,28 @@ test_that("forward-reverse transformation works for CRLF", {
   expect_true(all(ret))
 })
 
+test_that("forward-reverse transformation works for latin1", {
+  # c.f. rlang::mut_latin1_locale()
+  locale <- if (.Platform$OS.type == "windows") "English_United States.1252" else "en_US.ISO8859-1"
```
Comment (krlmlr) [inline tests/testthat/test-transform-lines.R]: I'd rather test this only on Windows, because locale names are inconsistent on other OS.

**Review by krlmlr — COMMENTED** [review]
Thanks, I agree that enc should convert to UTF-8 as necessary.

**Comment by krlmlr** [comment]
My AppVeyor settings are a mess right now, need to review eventually.

File: tests/testthat/test-transform-lines.R (hunk 1 above)
Comment (yutannihilation) [reply tests/testthat/test-transform-lines.R]: I see.

**Comment by krlmlr** [comment]
Thanks!
